services:
  postgres-db:
    image: postgres:17.6-alpine
    restart: always
    command: -c 'max_connections=1024'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "password"
    volumes:
      - "../../.local/postgresql:/var/lib/postgresql/data"
      - "./pg-init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
      - "5433:5432"
