[package]
name = "logging"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
