[package]
name = "jwt_auth"
edition = "2024"
version.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true

# Internal dependencies
random_util.workspace = true
jwt_signer.workspace = true
error.workspace = true
