# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
patch_file = "src/schema.patch"

# Exclude table from PostGIS extension
filter = { except_tables = ["spatial_ref_sys"] }

[migrations_directory]
dir = "migrations"
